=== Julie717/Parsing/src/main/resources/candy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/candies"
        xmlns:tns="http://www.example.com/candies"
        elementFormDefault="qualified">
    <element name="candy" type="tns:Candy" abstract="true"/>
    <element name="caramel" type="tns:Caramel" substitutionGroup="tns:candy"/>
    <element name="chocolate-candy" type="tns:ChocolateCandy" substitutionGroup="tns:candy"/>
    <element name="candies">
        <complexType>
            <sequence>
                <element ref="tns:candy" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Candy">
        <sequence>
            <element name="value" type="tns:Value"/>
            <element name="energy" type="nonNegativeInteger"/>
            <element name="production-date" type="date"/>
            <element name="production" default="Kommunarka">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Kommunarka"></enumeration>
                        <enumeration value="Spartak"></enumeration>
                        <enumeration value="Roshen"></enumeration>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
        <attribute name="id" use="required">
            <simpleType>
                <restriction base="ID">
                    <pattern value="N\d{1,10}"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="name" use="optional" default="Candy">
            <simpleType>
                <restriction base="string">
                    <pattern value="([\d\w])+(\s[\d\w]+)*"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
    <complexType name="Caramel">
        <complexContent>
            <extension base="tns:Candy">
                <sequence>
                    <element name="type-caramel" type="tns:TypeCaramel"/>
                    <element name="caramel-ingredients" type="tns:CaramelIngredients"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="ChocolateCandy">
        <complexContent>
            <extension base="tns:Candy">
                <sequence>
                    <element name="chocolate-type" type="tns:ChocolateType"/>
                    <element name="filling-type" type="tns:FillingType"/>
                    <element name="chocolate-candy-ingredients" type="tns:ChocolateCandyIngredients"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="Value">
        <sequence>
            <element name="proteins" type="nonNegativeInteger"/>
            <element name="fats" type="nonNegativeInteger"/>
            <element name="carbohydrates" type="nonNegativeInteger"/>
        </sequence>
    </complexType>
    <complexType name="CaramelIngredients">
        <sequence>
            <element name="sugar" type="nonNegativeInteger"/>
            <element name="vanilla" type="nonNegativeInteger"/>
            <element name="fructose" type="nonNegativeInteger"/>
            <element name="molasses" type="nonNegativeInteger"/>
            <element name="condensed-milk" type="nonNegativeInteger"/>
            <element name="applesauce" type="nonNegativeInteger"/>
        </sequence>
    </complexType>
    <complexType name="ChocolateCandyIngredients">
        <sequence>
            <element name="sugar" type="nonNegativeInteger"/>
            <element name="vanilla" type="nonNegativeInteger"/>
            <element name="fructose" type="nonNegativeInteger"/>
            <element name="butter" type="nonNegativeInteger"/>
            <element name="cream" type="nonNegativeInteger"/>
            <element name="pastry-fat">
                <simpleType>
                    <restriction base="nonNegativeInteger">
                        <maxExclusive value="100"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>
    <simpleType name="TypeCaramel">
        <restriction base="string">
            <enumeration value="Lollipop"></enumeration>
            <enumeration value="Jelly Beans"></enumeration>
            <enumeration value="Stuffed caramel"></enumeration>
        </restriction>
    </simpleType>
    <simpleType name="ChocolateType">
        <restriction base="string">
            <enumeration value="Milk"></enumeration>
            <enumeration value="Dark"></enumeration>
            <enumeration value="Black"></enumeration>
            <enumeration value="White"></enumeration>
        </restriction>
    </simpleType>
    <simpleType name="FillingType">
        <restriction base="string">
            <enumeration value="Toffee"></enumeration>
            <enumeration value="Truffle"></enumeration>
            <enumeration value="Waffle"></enumeration>
            <enumeration value="Grilyazh"></enumeration>
        </restriction>
    </simpleType>
</schema>

=== Julie717/Parsing/src/main/resources/candy.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/candies"
         xsi:schemaLocation="http://www.example.com/candies candy.xsd">
    <caramel id="N1" name="Critters">
        <value>
            <proteins>0</proteins>
            <fats>100</fats>
            <carbohydrates>98000</carbohydrates>
        </value>
        <energy>390</energy>
        <production-date>2020-05-04</production-date>
        <production>Kommunarka</production>
        <type-caramel>Lollipop</type-caramel>
        <caramel-ingredients>
            <sugar>50000</sugar>
            <vanilla>2000</vanilla>
            <fructose>0</fructose>
            <molasses>0</molasses>
            <condensed-milk>0</condensed-milk>
            <applesauce>0</applesauce>
        </caramel-ingredients>
    </caramel>
    <chocolate-candy id="N2" name="Mont Blanc">
        <value>
            <proteins>8000</proteins>
            <fats>40700</fats>
            <carbohydrates>45300</carbohydrates>
        </value>
        <energy>580</energy>
        <production-date>2020-09-01</production-date>
        <production>Roshen</production>
        <chocolate-type>Milk</chocolate-type>
        <filling-type>Toffee</filling-type>
        <chocolate-candy-ingredients>
            <sugar>10000</sugar>
            <vanilla>0</vanilla>
            <fructose>0</fructose>
            <butter>40000</butter>
            <cream>10000</cream>
            <pastry-fat>20</pastry-fat>
        </chocolate-candy-ingredients>
    </chocolate-candy>
    <chocolate-candy id="N3">
        <value>
            <proteins>10000</proteins>
            <fats>37000</fats>
            <carbohydrates>50000</carbohydrates>
        </value>
        <energy>497</energy>
        <production-date>2020-05-27</production-date>
        <production></production>
        <chocolate-type>Dark</chocolate-type>
        <filling-type>Truffle</filling-type>
        <chocolate-candy-ingredients>
            <sugar>9000</sugar>
            <vanilla>2</vanilla>
            <fructose>0</fructose>
            <butter>30000</butter>
            <cream>0</cream>
            <pastry-fat>25</pastry-fat>
        </chocolate-candy-ingredients>
    </chocolate-candy>
</candies>
